### ISSUE TITLE
repo permissions...

### ISSUE THREAD

**Issue by infopirate** [smith-kyle/electron-background-process-app#2]
Permission denied (publickey).
 when i attempted to run git clone git@github.com:smith-kyle/electron-background-process-app.git

**Comment by smith-kyle** [comment]
Is your ssh key added to github? Here are instructions for adding an ssh key to github

https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

Or if you'd prefer you can clone with https: `git clone https://github.com/smith-kyle/electron-background-process-app.git`
